parameters: []
stages:

- stage: Build
  displayName: Build Stage
  jobs:

  - job: Build
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
       repository: $(ImageName)
       command: buildAndPush
       containerRegistry: HomeAutomationContainerRegistry
       Dockerfile: $(DockerfileLocation)
       buildContext: $(SolutionDirectory)
       tags: |
        $(Build.BuildId)

- stage: Dev_QA
  displayName: DEV/QA
  jobs:

  - job: Dev_QA_Deployment
    steps:

    - pwsh: Write-Host "Placeholder Stage for Deployment"

