stages:

- stage: Build
  displayName: Build Stage
  jobs:

  - job: Build
    steps:
      
    - task: Docker@2
      displayName: Build an image
      inputs:
       repository: $(ImageName)
       command: build
       Dockerfile: $(DockerfileLocation)
       buildContext: $(SolutionDirectory)
       tags: |
        $(Build.BuildId)
