parameters: []
stages:

- stage: GatedBuild
  displayName: Gated Build Stage
  jobs:

  - job: GatedBuild
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
       repository: $(ImageName)
       command: build
       Dockerfile: $(DockerfileLocation)
       buildContext: $(SolutionDirectory)
       tags: |
        $(Build.BuildId)
