# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  ImageName: 'hub-service'
  SolutionDirectory: '$(System.DefaultWorkingDirectory)/HubService'
  DockerfileLocation: '$(SolutionDirectory)/HubService/Dockerfile'

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
   repository: $(ImageName)
   command: buildAndPush
   containerRegistry: HomeAutomationContainerRegistry
   Dockerfile: $(DockerfileLocation)
   buildContext: $(SolutionDirectory)
   tags: |
    $(Build.BuildId)
