# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  ImageName: 'hub-service'

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
   repository: $(ImageName)
   command: build
   Dockerfile: HubService/Dockerfile
